services:
  web:
    build: .
    container_name: resume-builder
    volumes: .:/app
    depends_on:
      - db
    env_file:
      - .env
    network:
      - resume-builder
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes: ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - resume-builder
  
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_db:/var/lib/posgressql/data
    networks:
      - resume-builder
voulumes:
  postgres_db:

networks:
  resume-builder:
    external: true
    name: ${NETWORK_NAME}
